/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;

/**
 *
 * @author AntônioVieira
 */
public class Jogo2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jogo2.class.getName());

    /**
     * Creates new form Jogo2
     */
    
     // JButton precisa da importação da sua biblioteca
    //CONTRUTOR DA CLASSE/TELA - SEM ELE A TELA NÃO FUNCIONA
    // matriz com - 10 linhas e 10 colunas
    
    JButton [][] btnCampos = new JButton[10][10];
    
   //MATRIZ PARA GUARDAR AS BOMBAS - TRUE P/ BOMBA, FALSE P/ NUMEROS 
    boolean [][] bombas = new boolean [10][10];
    
    // MATRIZ PARA GUARDAR OS CAMOS QUE FOREM ABERTAS
    boolean [][] abertos = new boolean[10][10];
    
    int quantidadeBombas = 15;
    boolean jogoEncerrado= false;
    
    public Jogo2() {
        initComponents();
        CriarTabuleiro();
    }

    //CRIAR AS NOSSA FUNÇÕES/METODOS
  public void CriarTabuleiro(){
  //definir que o painel será divido em 10 linhas e colunas
  // com altura 2px e largura 2px
  painelCampo.setLayout( new GridLayout(10,10,2,2));// GridLayout divide     
  
  for(int coluna=0;coluna<=9;coluna++){
  for(int linha=0;linha<=9;linha++){
  // váriavel botão para guardar os provisorios
  JButton  botao= new JButton();
   botao.setFont(new Font("Arial",Font.BOLD,16));// fonte
   botao.setBackground(new Color(60,59,59));// cor de fundo
   botao.setForeground(Color.WHITE);// cor de texto
  
   // remover marcas do botão quem por padrão
   botao.setFocusPainted(false);
   botao.setEnabled(false);
   
   //adicionar o batão dentro da matriz
   btnCampos[linha][coluna]=botao;
  //adicionar ele dentro do painel
  painelCampo.add(botao);
   
   
  }// fim do segundo for
  }// fim do primeiro for
  }//fim do metodo CriarTabuleiro    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        tfTempo = new javax.swing.JTextField();
        painelCampo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setBackground(new java.awt.Color(204, 204, 204));
        titulo.setFont(new java.awt.Font("Segoe UI Black", 1, 32)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 51, 51));
        titulo.setText(" Campo Minado");

        btnIniciar.setBackground(new java.awt.Color(0, 51, 51));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(0, 153, 0));
        btnIniciar.setText("INICIAR");

        tfTempo.setEditable(false);
        tfTempo.setBackground(new java.awt.Color(0, 51, 51));
        tfTempo.setForeground(new java.awt.Color(255, 0, 0));
        tfTempo.setText("00:00");

        painelCampo.setBackground(new java.awt.Color(204, 204, 204));
        painelCampo.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout painelCampoLayout = new javax.swing.GroupLayout(painelCampo);
        painelCampo.setLayout(painelCampoLayout);
        painelCampoLayout.setHorizontalGroup(
            painelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        painelCampoLayout.setVerticalGroup(
            painelCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo)
                .addGap(161, 161, 161)
                .addComponent(btnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(painelCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jogo2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPanel painelCampo;
    private javax.swing.JTextField tfTempo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
